# Generated by Django 4.1.3 on 2022-12-11 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_movie_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='sdesc',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
